version: '3.8'

services:
  backend:
    build:
      context: ./company_api
      dockerfile: Dockerfile
    restart: always
    ports:
     - 8000:8000
    env_file: ./.env
    volumes:
      - static:/backend_static/static/
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    env_file: ./.env
    volumes:
      - db_postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
    depends_on:
      - backend


volumes:
  db_postgresql:
  static: