# Generated by Django 5.0 on 2023-12-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_position_name_position_unique_name_division'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ('name',), 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterModelOptions(
            name='employeeposition',
            options={'ordering': ('position',), 'verbose_name': 'Должность сотрудника', 'verbose_name_plural': 'Должности сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='positionpermission',
            options={'ordering': ('position',), 'verbose_name': 'Должностное прао', 'verbose_name_plural': 'Должностные права'},
        ),
    ]
